### ISSUE TITLE
Documentation Problem

### ISSUE THREAD

**Issue by sanjay7178** [sinisterdaddy/DEXI#1]
[Active Faculty DataN.csv](https://github.com/sinisterdaddy/DEXI/blob/main/Active%20Faculty%20DataN.csv) is made public, this can used for unethical purposes

**Comment by radhagarg** [comment]
solved

**Comment by sanjay7178** [comment]
> solved

The data can be retrieved from this [point](https://github.com/sinisterdaddy/DEXI/tree/4cd8c71d6fe7081a58dc9a2e9b63386a4efcdc71)
